image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: v2.5.0
  pullPolicy: IfNotPresent
manifestManager:
  enabled: true
workload:
  main:
    podSpec:
      initContainers:
        main:
          type: install
          enabled: true
          imageSelector: image
          securityContext:
            runAsUser: 100
            runAsGroup: 100
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
        volumes:
          - name: certs
          secret:
            secretName: cert-manager-webhook-pdns-webhook-tls  
      containers:
        main:
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
          env:
            GROUP_NAME: "acme.zacharyseguin.ca"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          probes:
            liveness:
              enabled: true
              path: /healthz
              port: https
            readiness:
              enabled: true
              path: /healthz
              port: https
            startup:
              enabled: false
service:
  main:
    ports:
      main:
        port: 8443
        protocol: https
        targetPort: 8443
portal:
  open:
    enabled: false

groupName: acme.zacharyseguin.ca

certManager:
  namespace: serviceAccountName: cert-manager-certmanager

nameOverride: ""
fullnameOverride: ""
