apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-pdns.serviceAccountName" . }}
  labels:
    app: {{ include "cert-manager-webhook-pdns.name" . }}
    chart: {{ include "cert-manager-webhook-pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
