image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: latest@sha256:a01f9a54bc2a32fd72a0df79d0e27450c7f20f1122b2463ca665d80fa6acedd9
  pullPolicy: IfNotPresent
manifestManager:
  enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            GROUP_NAME: "acme.mycompany.com"
          probes:
            liveness:
              type: https
              path: /healthz
            readiness:
              type: https
              path: /healthz
            startup:
              enabled: false
service:
  main:
    ports:
      type: ClusterIP
      main:
        port: 443
        protocol: https
persistence:
  cert:
    enabled: true
    mountPath: "/tls"
portal:
  open:
    enabled: false
operator:
  verify:
    additionalOperators:
      - cert-manager
    enabled: true
    failOnError: false
groupName: acme.mycompany.com
certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager
webhookPdns:
  serverID: localhost
  ttl: 120
  timeout: 30
  caBundle: BASE64_ENCODED_CA_BUNDLE
nameOverride: ""
fullnameOverride: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
