image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: v2.5.0
  pullPolicy: IfNotPresent

groupName: acme.zacharyseguin.ca

certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager

nameOverride: ""
fullnameOverride: ""

service:
  main:
    type: ClusterIP
    ports:
      main:
        protocol: tcp
        port: 443
        targetPort: 8443

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
          probes:
            liveness:
              enabled: true
              path: "/healthz"
              type: https
              port: 8443
            readiness:
              enabled: true
              path: "/healthz"
              type: https
              port: 8443
            startup:
              enabled: false
          env:
            GROUP_NAME: acme.zacharyseguin.ca
persistence:
  certs:
    enabled: true
    mountPath: /tls
    readOnly: true
    type: secret
    objectName: webhook-tls
    optional: false
  varrun:
    enabled: false
  varlogs:
    enabled: false
  tmp:
    enabled: false
  shared:
    enabled: false
  devshm:
    enabled: false

securityContext:
  container:
    runAsGroup: 100
    runAsUser: 100

serviceAccount:
  main:
    enabled: true
    primary: true

podOptions:
  automountServiceAccountToken: true
