kubeVersion: ">=1.24.0-0"
apiVersion: v2
name: cert-manager-webhook-pdns
version: 1.2.2
description: Cert Manager Webhook for PowerDNS.
type: application
home: https://github.com/cyr-ius/cert-manager-webhook-pdns
icon: https://truecharts.org/img/hotlink-ok/chart-icons/clusterissuer.png
maintainers:
  - name: Cyr-ius
    email: webmaster@ipocus.net
    url: https://ipocus.net
appVersion: v1.1.4
annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: home-automation
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
dependencies:
  - name: common
    version: 20.3.13
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
sources:
  - https://github.com/cyr-ius/truenas-charts/tree/my-refs/charts/stable/cert-manager-webhook-pdns
keywords:
  - cert-manager
  - certificates
