groupName: acme.mycompany.com
certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager
image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: latest@sha256:a01f9a54bc2a32fd72a0df79d0e27450c7f20f1122b2463ca665d80fa6acedd9
  pullPolicy: IfNotPresent
webhook:
  serverID: localhost
  ttl: 120
  timeout: 30
  caBundle: BASE64_ENCODED_CA_BUNDLE
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 443
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
containerSecurityContext:
  runAsUser: 100
  runAsGroup: 100
podAnnotations: {}
podSecurityContext: {}
priorityClassName: ""
