image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: v2.5.0
  pullPolicy: IfNotPresent

groupName: acme.zacharyseguin.ca

certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager

nameOverride: ""
fullnameOverride: ""

service:
  main:
    ports:
      main:
        protocol: tcp
        port: 8443
        targetPort: 8443
  https:
    enabled: true
    ports:
      https:
        enabled: true
        protocol: https
        port: 443
        targetPort: 443

workload:
  main:
    podSpec:
      containers:
        main:
          args:
          - --tls-cert-file=/tls/tls.crt
          - --tls-private-key-file=/tls/tls.key
          - --secure-port=8443
          probes:
            liveness:
              path: "/healthz"
              type: https
              port: "{{ .Values.service.main.ports.main.targetPort }}"
            readiness:
              path: "/healthz"
              type: https
              port: "{{ .Values.service.main.ports.main.targetPort }}"
            startup:
              enabled: false
          env:
            GROUP_NAME: acme.zacharyseguin.ca
persistence:
  certs:
    enabled: true
    mountPath: /tls
    readOnly: true
    type: secret
    objectName:  cert-manager-webhook-pdns-webhook-tls
    optional: false
    expandObjectName: false
  varrun:
    enabled: true
  varlogs:
    enabled: true
  tmp:
    enabled: true
  shared:
    enabled: true
  devshm:
    enabled: true

securityContext:
  container:
    runAsGroup: 100
    runAsUser: 100
