image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: v2.5.0
  pullPolicy: IfNotPresent

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
          env:
            GROUP_NAME: "acme.zacharyseguin.ca"
          probes:
            liveness:
              type: https
              path: /healthz
            readiness:
              type: https
              path: /healthz
            startup:
              enabled: false
service:
  main:
    ports:
      main:
        port: 8443
        targetPort: 80
portal:
  open:
    enabled: false

groupName: acme.zacharyseguin.ca

certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager

nameOverride: ""
fullnameOverride: ""
