image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: v2.5.0
  pullPolicy: IfNotPresent

manifestManager:
  enabled: true

groupName: acme.zacharyseguin.ca

certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager

nameOverride: ""
fullnameOverride: ""

service:
  main:
    ports:
      main:
        protocol: TCP
        port: 8443

workload:
  main:
    podSpec:
      initContainers:
        init-config:
          type: install
          enabled: true
          env:
            GROUP_NAME: acme.zacharyseguin.ca
          volumeMounts:
          - mountPath: /tls
            name: certs
            readOnly: true
      containers:
        main:
          args:
          - --tls-cert-file=/tls/tls.crt
          - --tls-private-key-file=/tls/tls.key
          - --secure-port=8443
          probes:
            liveness:
              path: "/healthz"
              type: https
            readiness:
              path: "/healthz"
              type: https
            startup:
              enabled: false
          env:
            GROUP_NAME: acme.zacharyseguin.ca
          volumeMounts:
          - mountPath: /tls
            name: certs
            readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: cert-manager-webhook-pdns-webhook-tls

persistence:
  certs:
    secret:
      secretName: cert-manager-webhook-pdns-webhook-tls
  varrun:
    enabled: false
  varlogs:
    enabled: false
  tmp:
    enabled: false
  shared:
    enabled: false
  devshm:
    enabled: false

securityContext:
  container:
    runAsGroup: 100
    runAsUser: 100
