image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: v2.5.0
  pullPolicy: IfNotPresent

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
          env:
            GROUP_NAME: "acme.zacharyseguin.ca"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          probes:
            liveness:
              enabled: true
              path: /healthz
              port: https
            readiness:
              enabled: true
              path: /healthz
              port: https
            startup:
              enabled: false
              volumes:
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-pdns-webhook-tls
service:
  main:
    ports:
      main:
        port: 443
        protocol: https
        targetPort: 443
persistence:
  certs:
    enabled: true
    readOnly: true
    mountPath: "/tls"
portal:
  open:
    enabled: false

groupName: acme.zacharyseguin.ca

certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager

nameOverride: ""
fullnameOverride: ""
