image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: v2.5.0
  pullPolicy: IfNotPresent

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
          env:
            GROUP_NAME: "acme.zacharyseguin.ca"
          probes:
            liveness:
              type: https
              path: /healthz
            readiness:
              type: https
              path: /healthz
            startup:
              enabled: false
service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      main:
        enabled: true
        port: 443
        targetPort: 8443

portal:
  open:
    enabled: false

persistence:
  certs:
    enabled: true
    type: secret
    readOnly: true
    objectName: cert-manager-certmanager-tls
    mountPath: /tls

groupName: acme.zacharyseguin.ca

certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager

nameOverride: ""
fullnameOverride: ""
