image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: v2.5.0
  pullPolicy: IfNotPresent

groupName: acme.zacharyseguin.ca

certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager

nameOverride: ""
fullnameOverride: ""

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            - name: GROUP_NAME
              value: acme.zacharyseguin.ca
          volumeMounts:
            - mountPath: /tls
              name: certs
              readOnly: true
        volumes:
          - name: certs
            secret:
              secretName: cert-manager-webhook-pdns-webhook-tls
