image:
  repository: zachomedia/cert-manager-webhook-pdns
  tag: v2.5.0
  pullPolicy: IfNotPresent

manifestManager:
  enabled: true

groupName: acme.zacharyseguin.ca

certManager:
  namespace: ix-cert-manager
  serviceAccountName: cert-manager-certmanager

nameOverride: ""
fullnameOverride: ""

service:
  main:
    type: ClusterIP
    ports:
      main:
        enabled: true
        protocol: https
        port: 443

workload:
  main:
    podSpec:
      initContainers:
        init-config:
          type: install
          enabled: true
          env:
            GROUP_NAME: acme.zacharyseguin.ca
          volumeMounts:
          - mountPath: /tls
            name: certs
            readOnly: true
      containers:
        main:
          probes:
            liveness:
              path: "/healthz"
              type: https
            readiness:
              path: "/healthz"
              type: https
            startup:
              type: tcp
          env:
            GROUP_NAME: acme.zacharyseguin.ca
      volumes:
      - name: certs
        secret:
          secretName: cert-manager-webhook-pdns-webhook-tls

persistence:
  certs:
    enabled: true
    mountPath: /tls
    readOnly: true
  varrun:
    enabled: false
  varlogs:
    enabled: false
  tmp:
    enabled: false
  shared:
    enabled: false
  devshm:
    enabled: false
