kubeVersion: ">=1.24.0-0"
apiVersion: v2
name: home-assistant
version: 23.0.0
appVersion: 2023.12.3
description: home-assistant App for TrueNAS SCALE
home: https://truecharts.org/charts/stable/home-assistant
icon: https://truecharts.org/img/hotlink-ok/chart-icons/home-assistant.png
deprecated: false
sources:
  - https://github.com/cyr-ius/truenas-charts/tree/my-refs/charts/stable/home-assistant
  - https://github.com/home-assistant/home-assistant
  - https://github.com/cdr/code-server
maintainers:
  - email: cyr-ius@ipocus.net
    name: My Catalog
    url: https://github.com/cyr-ius/
keywords:
  - home-assistant
  - hass
  - homeassistant
dependencies:
  - name: common
    version: 19.0.0
    repository: https://library-charts.truecharts.org
    condition: ""
    alias: ""
    tags: []
    import-values: []
annotations:
  max_scale_version: 23.10.2
  min_scale_version: 23.10.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: home-automation
  truecharts.org/max_helm_version: "3.13"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
type: application
