apiVersion: v1
kind: Secret
metadata:
  name: pdns-api-key
  namespace: {{ .Values.certManager.namespace }}
  labels:
    {{- include "cert-manager-webhook-pdns.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.webhookPdns.apiKeySecretRef }}
